AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*

Documentation:
  Exclude:
    - spec/**/*

PredicateName:
  Exclude:
    - spec/**/*

StringLiterals:
  EnforcedStyle: double_quotes
