AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*
    - vendor/**/*
  RunRailsCops: true

Documentation:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 30

PredicateName:
  Exclude:
    - spec/**/*

StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 50

StringLiteralsInInterpolation:
  Enabled: false