inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - gemfiles/**/*
    - spec/dummy/**/*
    - vendor/**/*
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Documentation:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 30

ModuleLength:
  Exclude:
    - spec/**/*

PredicateName:
  Exclude:
    - spec/**/*

StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 50

StringLiteralsInInterpolation:
  Enabled: false
