AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*
    - vendor/**/*

Documentation:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 15

PredicateName:
  Exclude:
    - spec/**/*

StringLiterals:
  EnforcedStyle: double_quotes
